[package]
name = "concurrent_stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
rand = "0.8.5"
[dependencies.tokio]
version = "1.34.0"
features = ["full" ]
